/**
 * imports the scan and detection repositories to allow access
 * to their respective database functions,
 * and defines service functions
 */
const {spawn} = require('child_process');
const path = require('path'); // for constructing file paths suitable in a different platforms
const file_system = require('fs'); // for file system operations like reading/writing files
const scan_repository = require('../repositories/scan_repository');
const malware_repository = require('../repositories/malware_repository');
const detection_repository = require('../repositories/detection_repository');
const file_service = require('./file_service');
const yara_service = require('./yara_service');


// starts the path_scanner.py script as a child process, passing the target path and scan_id as arguments
const startPathScanner = (target_path, scan_id) => {
    return new Promise((resolve, reject) => {
        // creates the path where the scan report will be saved, using the scan ID to create a unique filename
        const output_path = path.join(__dirname, '..', '..', `scan_report_${scan_id}.json`);


        const args = [
            process.env.SCANNER_SCRIPT_PATH,
            '--sample', target_path,
            '--yara-rules-dir', process.env.YARA_RULES_DIR,
            '--scan-directories', path.dirname(target_path),
            '--cuckoo-api', process.env.CUCKOO_API_URL || 'http://localhost:8090',
            '--token', process.env.CUCKOO_TOKEN,
            '--timeout', process.env.CUCKOO_TIMEOUT || '300',
            '--output', output_path,
        ];


        const python_process = spawn(process.env.PYTHON_PATH || 'python', args);


        python_process.stdout.on('data', (data) => {
            console.log(`[Python engine]: ${data.toString()}`);
        });


        python_process.stderr.on('data', (data) => {
            console.error(`[Python engine]: ${data.toString()}`);
        });


        python_process.on('close', (code) => {
            if (code !== 0) {
                return reject(new Error(`Python process exited with code ${code}`));
            }
            

            // reads the generated scan report generated by the python script
            try {
                const report_data = file_system.readFileSync(output_path, 'utf-8');
                const report = JSON.parse(report_data);
                resolve(report);
            } catch (err) {
                reject(new Error(`Failed to read or parse the scan report: ${err.message}`));
            }
        });
    });
};


// extracts relevant detection information from the scan report
// and formats it into the structure expected by the saveDetections function
const extractDetectionsFromReport = (report) => {
    const findings = report?.['Scan summary']?.['Static analysis']?.findings || [];
    const detections = [];


    for (const a_finding of findings) {
        for (const a_match of a_finding.matches || []) {
            detections.push({
                file_path: a_finding.file,
                rule_name: a_match.rule,
                time_detected: new Date(),
                status: 'Ignored',
            });
        }
    }


    return detections;
}


module.exports = {
    // initiates a new scan, starts the python process, and saves the generated results
    initiateScan: async (target_path) => {
        const scan = await scan_repository.createScan(target_path, "Running");


        try {
            const report = await startPathScanner(target_path, scan.scan_id);
            const detections = extractDetectionsFromReport(report);
            await file_service.registerFile(target_path);
            

            if (detections.length > 0) {
                await module.exports.saveDetections(scan.scan_id, detections);
            } else {
                await scan_repository.updateScanStatus(scan.scan_id, 'Completed');
            }


            await scan_repository.updateScanEndTime(scan.scan_id, new Date());


            return {
                id: scan.scan_id,
                started_at: scan.started_at,
                status: 'Completed',
                detections: detections.length,
            };
        }


        catch (err) {
            console.error(`Error during scan process: ${err.message}`);
            await scan_repository.updateScanStatus(scan.scan_id, 'Failed');
            throw err;
        }
    },


    // retrieves a scan by its ID
    getScanById: async (id) => {
        const scan = await scan_repository.findById(id);
        
        if (!scan) {
            const error = new Error('No scan match found');
            error.status = 404;
            throw error;
        } else {
            return {
                id: scan.scan_id,
                started_at: scan.started_at,
                ended_at: scan.ended_at,
                status: scan.status,
            };
        }
    },


    // retrieves all scans
    getAllScans: async () => {
        const all_scans = await scan_repository.findAll();
        return all_scans.map(scan => ({
            id: scan.scan_id,
            started_at: scan.started_at,
            ended_at: scan.ended_at,
            status: scan.status,
        }));
    },

    
    // retrieves all detections for a specific scan ID
    getDetectionsByScanId: async (id) => {
        const detections = await detection_repository.findByScanId(id);
        return detections.map(d => ({
            file_path: d.file?.file_path ?? null,
            malware_name: d.malware?.name ?? null,
            yara_rule_name: d.yara_rule?.rule_name ?? null,
            status: d.status,
        }));
    },


    // saves detection results generated by the Python engine for a specific scan ID
    saveDetections: async (scan_id, detections) => {
        const scan = await scan_repository.findById(scan_id);
        if (!scan) {
            const error = new Error('No scan match found');
            error.status = 404;
            throw error;
        }

        const saved = [];

        for (const a_detection of detections) {

            // look up the file record by its path
            const file = await file_service.getFileByPath(a_detection.file_path);
            if (!file) {
                console.warn(`Skipping detection: file path not found in database: ${a_detection.file_path}`);
                continue;
            }

            // look up the yara rule by its name
            const rule = await yara_service.getRuleByName(a_detection.rule_name);
            if (!rule) {
                console.warn(`Skipping detection: YARA rule not found in database: ${a_detection.rule_name}`);
                continue;
            }

            // generate a new detection ID
            const all_detections = await detection_repository.findByScanId(scan_id);
            const total = await detection_repository.countAll();
            const detection_id = `d${String(total + saved.length + 1).padStart(3, '0')}`;

            const new_detection = await detection_repository.createDetection({
                detection_id,
                scan_id,
                file_id: file.file_id,
                malware_id: rule.malware_id,
                rule_id: rule.rule_id,
                time_detected: a_detection.time_detected || new Date(),
                status: a_detection.status || 'Ignored',
            });

            saved.push({
                detection_id: new_detection.detection_id,
                file_path: a_detection.file_path,
                rule_name: a_detection.rule_name,
                status: new_detection.status,
            });
        }

        // update the scan status to Completed
        await scan_repository.updateScanStatus(scan_id, 'Completed');

        return { scan_id, detections_saved: saved.length, detections: saved };
    },
};